name: Perfumehub API Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.2"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        AUTH_SECRET: fake_auth_secret
        UNSUB_SECRET: fake_unsub_secret
        CRON_SECRET: fake_cron_secret
        GMAIL_ADDRESS: fake_mail@gmail.com
        FRONTEND_URL: http://localhost:5173
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest tests/
        